from gui.tabs.node_tab import NodeTab
from gui.tabs.group_tab import GroupTab
from gui.tabs.task_tab import TaskTab
from gui.tabs.file_transfer_tab import FileTransferTab
from gui.tabs.client_update_tab import ClientUpdateTab
from gui.tabs.batch_tab import BatchTab
from gui.tabs.remote_cmd_tab import RemoteCmdTab
from gui.tabs.monitor_tab import MonitorTab
from gui.tabs.log_tab import LogTab
